### ISSUE TITLE
Basic Documentation

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vds-player#77]
## Tasks

- [x] Build `custom-elements.json` file.
- [x] Use `custom-elements.json` to output basic documentation in the `docs` folder.
- [x] Include quick start guide and reference to all components.
- [x] Host on GitHub Pages.

## References

- https://github.com/mihar-22/wcom-cli/tree/main/src/transform/transformers/markdown

**Comment by mihar-22** [comment]
https://github.com/vidstack/vds-player/tree/main/docs - It'll be improved as I improve the [CLI tool](https://github.com/mihar-22/wcom-cli).
