### ISSUE TITLE
Basic Player Component

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vds-player#8]
## Tasks

- [x] `PlayerState` interface ([reference](https://github.com/vime-js/vime/blob/master/core/src/components/core/player/PlayerProps.ts)).
- [x] Define basic events interface for Player/Providers/UI.
- [x] `PlayerContext` object ([reference](https://github.com/vidstack/player/blob/main/docs/architecture/architecture.md#ui)).
- [x] Connect and test connection between `PlayerContext` to `Player`.

## Notes

This is the first component required as it sits at the top of the component hierarchy. We'll start with the most basic player API:

**Properties**

- `src`
- `volume`
- `currentTime`
- `paused`
- `poster`
- `muted`
- `aspectRatio`
- `duration` _(readonly)_
- `buffered` _(readonly)_
- `isMobile` _(readonly)_
- `isTouch` _(readonly)_
- `isBuffering` _(readonly)_
- `isPlaying` _(readonly)_
- `hasPlaybackStarted` _(readonly)_
- `hasPlaybackEnded` _(readonly)_
- `isPlaybackReady` _(readonly)_
- `viewType` _(readonly)_
- `isAudioView` _(readonly)_
- `isVideoView` _(readonly)_
- `mediaType` _(readonly)_
- `isAudio` _(readonly)_
- `isVideo` _(readonly)_

**Events**

- `vds-src-change`
- `vds-volume-change`
- `vds-current-time-change`
- `vds-poster-change`
- `vds-buffered-change`
- `vds-buffering-change`
- `vds-aspect-ratio-change`
- `vds-play`
- `vds-pause`
- `vds-playing`
- `vds-duration-change`
- `vds-playback-start`
- `vds-playback-end`
- `vds-playback-ready`
- `vds-view-Type-change`
- `vds-media-Type-change`
- `vds-mobile-change`
- `vds-touch-change`
- `vds-error`

**UI Events**

- `vds-user-play-request`
- `vd-user-pause-request`
- `vds-user-mute-request`
- `vds-user-unmute-request`
- `vds-user-volume-change-request`
- `vds-user-current-time-change-request`

**Provider Events**

- `vds-provider-play`
- `vds-provider-pause`
- `vds-provider-playing`
- `vds-provider-buffered`
- `vds-provider-view-type-change`
- `vds-provider-media-type-change`
- `vds-provider-playback-ready`
- `vds-provider-playback-start`
- `vds-provider-playback-end`
- `vds-provider-current-time-change`
- `vds-provider-duration-change`
- `vds-provider-volume-change`
- `vds-provider-buffering-start`
- `vds-provider-buffering-end`
- `vds-provider-error`

## References

- https://github.com/vidstack/player/blob/main/docs/architecture/architecture.md#player
- https://github.com/vime-js/vime/tree/master/core/src/components/core/player
- https://github.com/vime-js/vime/blob/master/core/src/components/core/player/PlayerEvents.ts
